apiVersion: v1
kind: Service
metadata:
  name: object-store-service
spec:
  type: NodePort
  selector:
    app: object-store
  ports:
    - port: 80          # Service port (internal)
      targetPort: 8080  # Pod port (Spring Boot)
      nodePort: 30080   # External port (optional)

